// Copies the MatchDayBet (V3) ABI used by the subgraph into a typed TS module.
// Run after the contract ABI changes: `npm run sync-abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const source = fileURLToPath(new URL("../../subgraph/abis/MatchDayBet.json", import.meta.url));
const target = fileURLToPath(new URL("../src/lib/contract/abi.ts", import.meta.url));

const abi = JSON.parse(readFileSync(source, "utf8"));
writeFileSync(
  target,
  `// Generated by scripts/sync-abi.mjs from subgraph/abis/MatchDayBet.json. Do not edit.\n` +
    `export const matchDayBetAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`Wrote ${abi.length} ABI entries to src/lib/contract/abi.ts`);
